### PR TITLE
Update test_import.py

### PR DESCRIPTION
**Pull request by plouisross**
Updates to the directory designations represented by URLs [from "iGEM-distribution" to iGEM-test-distribution-package in the fixtures at lines 22,28,29,73

### CODE REVIEW

**Comment by jakebeal** [comment]
I see 13 failing tests - is that the expected number after this patch?

**Comment by plouisross** [comment]
Failing tests occurred prior to submission of this patch

**Comment by jakebeal** [comment]
Does this patch reduce the number of failing tests, or is it the same?

**Comment by mburridge96** [comment]
@jakebeal New working code has been merged that contain the stem /igem-engineering/test_package. Does this not need to equal the name of the repository?

**Comment by jakebeal** [comment]
@mburridge96 No, it doesn't need to match the name of the repository --- and in fact, it may be better that it _not_ do so in some cases. Remember, we eventually want to be able to freely migrate repositories between servers, and GitHub's URL convention isn't the same as the URL convention on others like BitBucket.

**Comment by mburridge96** [comment]
Closing this due to it now already being updated. Thanks @plouisross and @jakebeal !

**Pull request closed without merging**
